### ISSUE TITLE
CI?

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4-samples#5]
Do we  have CI for this repo? If yes, please ignore this issue.
It would be great to know when the examples in this repo break as we change Lean.
We can use Lean nightly builds to test the examples every night.

**Comment by lovettchris** [comment]
Yes there is see https://github.com/leanprover/lean4-samples/blob/main/.github/workflows/ci.yml

**Comment by Kha** [comment]
This one should probably have a nightly cron job as well?

**Comment by lovettchris** [comment]
Done: https://github.com/leanprover/lean4-samples/commit/0712e53ce002971382a4c3a9c5b154f71aeb21df
